-- ============================================================================
-- Oracle DDL - Create/Replace das tabelas usadas no projeto
-- Repositório: RLA-Registro-de-Limpeza
-- Observação: Oracle não suporta "CREATE OR REPLACE TABLE".
--             Este script faz "DROP TABLE ..." (se existir) e recria.
-- ============================================================================

-- --------------------------------------------------------------------------
-- 1) DROP das tabelas (na ordem correta por dependência)
-- --------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE if_tbl_registro_higiene CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE if_tbl_sala_higiene CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE if_tbl_setores_higiene CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE users_relatorio CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE registro_dispositivopermitido CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE registro_ippermitido CASCADE CONSTRAINTS PURGE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- --------------------------------------------------------------------------
-- 2) CREATE das tabelas
-- --------------------------------------------------------------------------

CREATE TABLE if_tbl_setores_higiene (
    id_setor     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome_setor   VARCHAR2(200 CHAR) NOT NULL,
    CONSTRAINT pk_if_tbl_setores_higiene PRIMARY KEY (id_setor)
);
/

CREATE TABLE if_tbl_sala_higiene (
    id_sala      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    nome_sala    VARCHAR2(200 CHAR) NOT NULL,
    id_setor     NUMBER(10) NOT NULL,
    sn_ativo     CHAR(1 CHAR) DEFAULT 'S' NOT NULL,
    CONSTRAINT pk_if_tbl_sala_higiene PRIMARY KEY (id_sala),
    CONSTRAINT fk_sala_setor FOREIGN KEY (id_setor)
        REFERENCES if_tbl_setores_higiene (id_setor),
    CONSTRAINT ck_if_tbl_sala_sn_ativo CHECK (sn_ativo IN ('S', 'N'))
);
/

CREATE TABLE if_tbl_registro_higiene (
    id_registro             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    id_sala                 NUMBER(10) NOT NULL,
    colaborador             CLOB,
    data_limpeza            DATE,
    hora_limpeza            VARCHAR2(8 CHAR),
    id_tipo_limpeza         NUMBER(3),
    obs                     VARCHAR2(1000 CHAR),
    portas                  VARCHAR2(5 CHAR),
    teto                    VARCHAR2(5 CHAR),
    paredes                 VARCHAR2(5 CHAR),
    janelas                 VARCHAR2(5 CHAR),
    piso                    VARCHAR2(5 CHAR),
    superficie_mobiliario   VARCHAR2(5 CHAR),
    dispenser               VARCHAR2(5 CHAR),
    id_criticidade          NUMBER(3),
    papel_hig               NUMBER(3) DEFAULT 0 NOT NULL,
    papel_toalha            NUMBER(3) DEFAULT 0 NOT NULL,
    alcool                  NUMBER(3) DEFAULT 0 NOT NULL,
    sabonete                NUMBER(3) DEFAULT 0 NOT NULL,
    device                  VARCHAR2(255 CHAR),
    last_update             DATE DEFAULT SYSDATE,
    CONSTRAINT pk_if_tbl_registro_higiene PRIMARY KEY (id_registro),
    CONSTRAINT fk_registro_sala FOREIGN KEY (id_sala)
        REFERENCES if_tbl_sala_higiene (id_sala),
    CONSTRAINT ck_if_tbl_reg_papel_hig CHECK (papel_hig BETWEEN 0 AND 999),
    CONSTRAINT ck_if_tbl_reg_papel_toalha CHECK (papel_toalha BETWEEN 0 AND 999),
    CONSTRAINT ck_if_tbl_reg_alcool CHECK (alcool BETWEEN 0 AND 999),
    CONSTRAINT ck_if_tbl_reg_sabonete CHECK (sabonete BETWEEN 0 AND 999)
);
/

CREATE TABLE registro_ippermitido (
    id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ip_address       VARCHAR2(45 CHAR) NOT NULL,
    descricao        VARCHAR2(200 CHAR),
    ativo            NUMBER(1) DEFAULT 1 NOT NULL,
    data_criacao     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_registro_ippermitido PRIMARY KEY (id),
    CONSTRAINT uq_registro_ippermitido_ip UNIQUE (ip_address),
    CONSTRAINT ck_registro_ippermitido_ativo CHECK (ativo IN (0,1))
);
/

CREATE TABLE registro_dispositivopermitido (
    id               NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    identificador    VARCHAR2(100 CHAR) NOT NULL,
    descricao        VARCHAR2(200 CHAR),
    ativo            NUMBER(1) DEFAULT 1 NOT NULL,
    data_criacao     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    data_atualizacao TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_registro_dispositivopermitido PRIMARY KEY (id),
    CONSTRAINT uq_registro_dispositivopermitido_id UNIQUE (identificador),
    CONSTRAINT ck_registro_dispositivo_ativo CHECK (ativo IN (0,1))
);
/

CREATE TABLE users_relatorio (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username      VARCHAR2(100 CHAR) NOT NULL,
    password      VARCHAR2(255 CHAR) NOT NULL,
    edit          NUMBER(1) DEFAULT 0 NOT NULL,
    ativo         NUMBER(1) DEFAULT 1 NOT NULL,
    data_criacao  TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_users_relatorio PRIMARY KEY (id),
    CONSTRAINT uq_users_relatorio_username UNIQUE (username),
    CONSTRAINT ck_users_relatorio_edit CHECK (edit IN (0,1)),
    CONSTRAINT ck_users_relatorio_ativo CHECK (ativo IN (0,1))
);
/

-- --------------------------------------------------------------------------
-- 3) Índices recomendados para as queries do projeto
-- --------------------------------------------------------------------------
CREATE INDEX idx_if_tbl_registro_higiene_sala ON if_tbl_registro_higiene (id_sala);
/

CREATE INDEX idx_if_tbl_registro_higiene_data_hora ON if_tbl_registro_higiene (data_limpeza DESC, hora_limpeza DESC);
/

CREATE INDEX idx_if_tbl_registro_higiene_tipo ON if_tbl_registro_higiene (id_tipo_limpeza);
/

CREATE INDEX idx_if_tbl_sala_higiene_setor ON if_tbl_sala_higiene (id_setor);
/

-- --------------------------------------------------------------------------
-- 4) COMMIT final
-- --------------------------------------------------------------------------
COMMIT;
/
