# Generated by Django 5.2.7 on 2025-10-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_dispositivopermitido'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Usuário')),
                ('password', models.CharField(max_length=255, verbose_name='Senha')),
                ('edit', models.BooleanField(default=False, help_text='Se ativo, o usuário NÃO pode acessar a view de edição', verbose_name='Permissão de Edição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Usuário de Relatório',
                'verbose_name_plural': 'Usuários de Relatório',
                'db_table': 'users_relatorio',
                'ordering': ['username'],
            },
        ),
        migrations.AlterField(
            model_name='dispositivopermitido',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descricao do dispositivo/local (ex: Tablet Sala 1B)', max_length=200, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='ippermitido',
            name='descricao',
            field=models.CharField(blank=True, help_text='Descrição do dispositivo/local (ex: Tablet Sala 1)', max_length=200, verbose_name='Descrição'),
        ),
    ]
